# Generated by Django 5.1.6 on 2025-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_article_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
